CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  alias VARCHAR(50) NOT NULL UNIQUE,
  bio TEXT,
  profile_picture_url VARCHAR(255),
  banner_picture_url VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
